name: Bug
description: A bug is an issue that describes a problem with the software. It should include steps to reproduce the issue, expected behavior, and actual behavior.
labels: bug
type: Bug
projects: 
  - astro-panda/20
body:
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe what actually happened.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step description of how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional information that may be helpful in diagnosing the issue. This can include screenshots, logs, or any other relevant details.
  